centos_6:
    spec: monitoring-packs-sfl-windows-mssql.spec
    deps_pip:
        - sphinx
centos_7:
    spec: monitoring-packs-sfl-windows-mssql.spec
    deps_pip:
        - sphinx
debian_8:
    debian: debian
ubuntu_12.04:
    debian: debian
ubuntu_14.04:
    debian: debian
